// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAckV13rjrS14o9hC1QDIEXTUrdZLu4z_o',
    appId: '1:319158977737:web:65599e0e835ed25f257918',
    messagingSenderId: '319158977737',
    projectId: 'hctssapp',
    authDomain: 'hctssapp.firebaseapp.com',
    storageBucket: 'hctssapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGDZ831MxEmK-Wn7PuCCNnUtErQexmccg',
    appId: '1:319158977737:android:84789c10f85cd615257918',
    messagingSenderId: '319158977737',
    projectId: 'hctssapp',
    storageBucket: 'hctssapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwDsRq4IG25Mf_t91QPlkMcHOT6FyRgg4',
    appId: '1:319158977737:ios:b35c152871fcaf05257918',
    messagingSenderId: '319158977737',
    projectId: 'hctssapp',
    storageBucket: 'hctssapp.firebasestorage.app',
    iosBundleId: 'com.example.citasPacienteFunesami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwDsRq4IG25Mf_t91QPlkMcHOT6FyRgg4',
    appId: '1:319158977737:ios:b35c152871fcaf05257918',
    messagingSenderId: '319158977737',
    projectId: 'hctssapp',
    storageBucket: 'hctssapp.firebasestorage.app',
    iosBundleId: 'com.example.citasPacienteFunesami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAckV13rjrS14o9hC1QDIEXTUrdZLu4z_o',
    appId: '1:319158977737:web:7b7871176b465d66257918',
    messagingSenderId: '319158977737',
    projectId: 'hctssapp',
    authDomain: 'hctssapp.firebaseapp.com',
    storageBucket: 'hctssapp.firebasestorage.app',
  );
}
