// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpoI4msW4oc3sMlApU0S-GLjXI8YedBWE',
    appId: '1:363946695455:web:placeholder',
    messagingSenderId: '363946695455',
    projectId: 'funesamiapphc',
    authDomain: 'funesamiapphc.firebaseapp.com',
    storageBucket: 'funesamiapphc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpoI4msW4oc3sMlApU0S-GLjXI8YedBWE',
    appId: '1:363946695455:android:a6bba90881cce96de2ae2a',
    messagingSenderId: '363946695455',
    projectId: 'funesamiapphc',
    storageBucket: 'funesamiapphc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpoI4msW4oc3sMlApU0S-GLjXI8YedBWE',
    appId: '1:363946695455:ios:placeholder',
    messagingSenderId: '363946695455',
    projectId: 'funesamiapphc',
    storageBucket: 'funesamiapphc.firebasestorage.app',
    iosBundleId: 'app.funesami.citas-paciente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpoI4msW4oc3sMlApU0S-GLjXI8YedBWE',
    appId: '1:363946695455:ios:placeholder',
    messagingSenderId: '363946695455',
    projectId: 'funesamiapphc',
    storageBucket: 'funesamiapphc.firebasestorage.app',
    iosBundleId: 'app.funesami.citas-paciente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpoI4msW4oc3sMlApU0S-GLjXI8YedBWE',
    appId: '1:363946695455:web:placeholder',
    messagingSenderId: '363946695455',
    projectId: 'funesamiapphc',
    authDomain: 'funesamiapphc.firebaseapp.com',
    storageBucket: 'funesamiapphc.firebasestorage.app',
  );
}
